set(OPEN_RIVAL_SOURCES
    ${OPEN_RIVAL_DIR}/src/Animations.cpp
    ${OPEN_RIVAL_DIR}/src/Application.cpp
    ${OPEN_RIVAL_DIR}/src/ApplicationContext.cpp
    ${OPEN_RIVAL_DIR}/src/AtlasRenderable.cpp
    ${OPEN_RIVAL_DIR}/src/AudioSystem.cpp
    ${OPEN_RIVAL_DIR}/src/AudioUtils.cpp
    ${OPEN_RIVAL_DIR}/src/BinaryFileReader.cpp
    ${OPEN_RIVAL_DIR}/src/Building.cpp
    ${OPEN_RIVAL_DIR}/src/BuildingAnimationComponent.cpp
    ${OPEN_RIVAL_DIR}/src/BuildingDef.cpp
    ${OPEN_RIVAL_DIR}/src/BuildingPropsComponent.cpp
    ${OPEN_RIVAL_DIR}/src/Camera.cpp
    ${OPEN_RIVAL_DIR}/src/Color.cpp
    ${OPEN_RIVAL_DIR}/src/Cursor.cpp
    ${OPEN_RIVAL_DIR}/src/Entity.cpp
    ${OPEN_RIVAL_DIR}/src/EntityComponent.cpp
    ${OPEN_RIVAL_DIR}/src/EntityFactory.cpp
    ${OPEN_RIVAL_DIR}/src/EntityRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/FacingComponent.cpp
    ${OPEN_RIVAL_DIR}/src/FileUtils.cpp
    ${OPEN_RIVAL_DIR}/src/FlyerComponent.cpp
    ${OPEN_RIVAL_DIR}/src/Font.cpp
    ${OPEN_RIVAL_DIR}/src/Framebuffer.cpp
    ${OPEN_RIVAL_DIR}/src/FramebufferRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/GLUtils.cpp
    ${OPEN_RIVAL_DIR}/src/GameCommand.cpp
    ${OPEN_RIVAL_DIR}/src/GameInterface.cpp
    ${OPEN_RIVAL_DIR}/src/GameRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/GameState.cpp
    ${OPEN_RIVAL_DIR}/src/Image.cpp
    ${OPEN_RIVAL_DIR}/src/InputUtils.cpp
    ${OPEN_RIVAL_DIR}/src/InventoryComponent.cpp
    ${OPEN_RIVAL_DIR}/src/JsonUtils.cpp
    ${OPEN_RIVAL_DIR}/src/Main.cpp
    ${OPEN_RIVAL_DIR}/src/MapBorderRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/MapUtils.cpp
    ${OPEN_RIVAL_DIR}/src/MathUtils.cpp
    ${OPEN_RIVAL_DIR}/src/MenuTextRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/MidiContainer.cpp
    ${OPEN_RIVAL_DIR}/src/MidiFile.cpp
    ${OPEN_RIVAL_DIR}/src/MidiPlayer.cpp
    ${OPEN_RIVAL_DIR}/src/MidsDecoder.cpp
    ${OPEN_RIVAL_DIR}/src/MouseHandlerComponent.cpp
    ${OPEN_RIVAL_DIR}/src/MousePicker.cpp
    ${OPEN_RIVAL_DIR}/src/MouseUtils.cpp
    ${OPEN_RIVAL_DIR}/src/MoveCommand.cpp
    ${OPEN_RIVAL_DIR}/src/MovementComponent.cpp
    ${OPEN_RIVAL_DIR}/src/OwnerComponent.cpp
    ${OPEN_RIVAL_DIR}/src/Palette.cpp
    ${OPEN_RIVAL_DIR}/src/PaletteUtils.cpp
    ${OPEN_RIVAL_DIR}/src/PassabilityComponent.cpp
    ${OPEN_RIVAL_DIR}/src/PathUtils.cpp
    ${OPEN_RIVAL_DIR}/src/Pathfinding.cpp
    ${OPEN_RIVAL_DIR}/src/PlayerContext.cpp
    ${OPEN_RIVAL_DIR}/src/PlayerState.cpp
    ${OPEN_RIVAL_DIR}/src/PortraitComponent.cpp
    ${OPEN_RIVAL_DIR}/src/ProgramOptions.cpp
    ${OPEN_RIVAL_DIR}/src/Rect.cpp
    ${OPEN_RIVAL_DIR}/src/RenderUtils.cpp
    ${OPEN_RIVAL_DIR}/src/Resources.cpp
    ${OPEN_RIVAL_DIR}/src/ScenarioBuilder.cpp
    ${OPEN_RIVAL_DIR}/src/ScenarioReader.cpp
    ${OPEN_RIVAL_DIR}/src/SeafarerComponent.cpp
    ${OPEN_RIVAL_DIR}/src/ShaderUtils.cpp
    ${OPEN_RIVAL_DIR}/src/Shaders.cpp
    ${OPEN_RIVAL_DIR}/src/SoundSource.cpp
    ${OPEN_RIVAL_DIR}/src/Sounds.cpp
    ${OPEN_RIVAL_DIR}/src/SpriteComponent.cpp
    ${OPEN_RIVAL_DIR}/src/SpriteRenderable.cpp
    ${OPEN_RIVAL_DIR}/src/Spritesheet.cpp
    ${OPEN_RIVAL_DIR}/src/State.cpp
    ${OPEN_RIVAL_DIR}/src/StringUtils.cpp
    ${OPEN_RIVAL_DIR}/src/TextRenderable.cpp
    ${OPEN_RIVAL_DIR}/src/TextRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/Texture.cpp
    ${OPEN_RIVAL_DIR}/src/TextureAtlas.cpp
    ${OPEN_RIVAL_DIR}/src/Tile.cpp
    ${OPEN_RIVAL_DIR}/src/TileRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/TimeUtils.cpp
    ${OPEN_RIVAL_DIR}/src/UiRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/UnitAnimationComponent.cpp
    ${OPEN_RIVAL_DIR}/src/UnitDef.cpp
    ${OPEN_RIVAL_DIR}/src/UnitPropsComponent.cpp
    ${OPEN_RIVAL_DIR}/src/VoiceComponent.cpp
    ${OPEN_RIVAL_DIR}/src/WalkerComponent.cpp
    ${OPEN_RIVAL_DIR}/src/WallComponent.cpp
    ${OPEN_RIVAL_DIR}/src/WaveFile.cpp
    ${OPEN_RIVAL_DIR}/src/Window.cpp
    ${OPEN_RIVAL_DIR}/src/World.cpp
    ${OPEN_RIVAL_DIR}/src/commands/GameCommandFactory.cpp
    ${OPEN_RIVAL_DIR}/src/gfx/BoxRenderable.cpp
    ${OPEN_RIVAL_DIR}/src/gfx/TextureRenderable.cpp
    ${OPEN_RIVAL_DIR}/src/lobby/LobbyState.cpp
    ${OPEN_RIVAL_DIR}/src/net/ClientInfo.cpp
    ${OPEN_RIVAL_DIR}/src/net/Connection.cpp
    ${OPEN_RIVAL_DIR}/src/net/PacketFactory.cpp
    ${OPEN_RIVAL_DIR}/src/net/Server.cpp
    ${OPEN_RIVAL_DIR}/src/net/Socket.cpp
    ${OPEN_RIVAL_DIR}/src/net/WindowsNetUtils.cpp
    ${OPEN_RIVAL_DIR}/src/net/packet-handlers/AcceptPlayerPacketHandler.cpp
    ${OPEN_RIVAL_DIR}/src/net/packet-handlers/GameCommandPacketHandler.cpp
    ${OPEN_RIVAL_DIR}/src/net/packet-handlers/KickPlayerPacketHandler.cpp
    ${OPEN_RIVAL_DIR}/src/net/packet-handlers/LobbyWelcomePacketHandler.cpp
    ${OPEN_RIVAL_DIR}/src/net/packet-handlers/PacketHandler.cpp
    ${OPEN_RIVAL_DIR}/src/net/packet-handlers/RejectPlayerPacketHandler.cpp
    ${OPEN_RIVAL_DIR}/src/net/packet-handlers/RequestJoinPacketHandler.cpp
    ${OPEN_RIVAL_DIR}/src/net/packet-handlers/StartGamePacketHandler.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/AcceptPlayerPacket.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/GameCommandPacket.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/KickPlayerPacket.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/LobbyWelcomePacket.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/Packet.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/RejectPlayerPacket.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/RelayedPacket.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/RequestJoinPacket.cpp
    ${OPEN_RIVAL_DIR}/src/net/packets/StartGamePacket.cpp
    ${OPEN_RIVAL_DIR}/src/platform/unix/UnixTimeUtils.cpp
    ${OPEN_RIVAL_DIR}/src/platform/win32/WindowsSocket.cpp
    ${OPEN_RIVAL_DIR}/src/platform/win32/WindowsTimeUtils.cpp
    ${OPEN_RIVAL_DIR}/src/ui/CursorRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/ui/MenuRenderer.cpp
    ${OPEN_RIVAL_DIR}/src/utils/BufferUtils.cpp
)

set(OPEN_RIVAL_INCLUDE_HEADERS
    ${OPEN_RIVAL_DIR}/include/Animations.h
    ${OPEN_RIVAL_DIR}/include/Application.h
    ${OPEN_RIVAL_DIR}/include/ApplicationContext.h
    ${OPEN_RIVAL_DIR}/include/AtlasRenderable.h
    ${OPEN_RIVAL_DIR}/include/AudioSystem.h
    ${OPEN_RIVAL_DIR}/include/AudioUtils.h
    ${OPEN_RIVAL_DIR}/include/BinaryFileReader.h
    ${OPEN_RIVAL_DIR}/include/Building.h
    ${OPEN_RIVAL_DIR}/include/BuildingAnimationComponent.h
    ${OPEN_RIVAL_DIR}/include/BuildingDef.h
    ${OPEN_RIVAL_DIR}/include/BuildingPropsComponent.h
    ${OPEN_RIVAL_DIR}/include/Camera.h
    ${OPEN_RIVAL_DIR}/include/Color.h
    ${OPEN_RIVAL_DIR}/include/ConfigUtils.h
    ${OPEN_RIVAL_DIR}/include/Cursor.h
    ${OPEN_RIVAL_DIR}/include/Entity.h
    ${OPEN_RIVAL_DIR}/include/EntityComponent.h
    ${OPEN_RIVAL_DIR}/include/EntityFactory.h
    ${OPEN_RIVAL_DIR}/include/EntityRenderer.h
    ${OPEN_RIVAL_DIR}/include/EntityUtils.h
    ${OPEN_RIVAL_DIR}/include/EnumUtils.h
    ${OPEN_RIVAL_DIR}/include/FacingComponent.h
    ${OPEN_RIVAL_DIR}/include/FileUtils.h
    ${OPEN_RIVAL_DIR}/include/FlyerComponent.h
    ${OPEN_RIVAL_DIR}/include/Font.h
    ${OPEN_RIVAL_DIR}/include/Framebuffer.h
    ${OPEN_RIVAL_DIR}/include/FramebufferRenderer.h
    ${OPEN_RIVAL_DIR}/include/GLUtils.h
    ${OPEN_RIVAL_DIR}/include/GameCommand.h
    ${OPEN_RIVAL_DIR}/include/GameInterface.h
    ${OPEN_RIVAL_DIR}/include/GameRenderer.h
    ${OPEN_RIVAL_DIR}/include/GameState.h
    ${OPEN_RIVAL_DIR}/include/Image.h
    ${OPEN_RIVAL_DIR}/include/InputUtils.h
    ${OPEN_RIVAL_DIR}/include/InventoryComponent.h
    ${OPEN_RIVAL_DIR}/include/JsonUtils.h
    ${OPEN_RIVAL_DIR}/include/MapBorderRenderer.h
    ${OPEN_RIVAL_DIR}/include/MapUtils.h
    ${OPEN_RIVAL_DIR}/include/MathUtils.h
    ${OPEN_RIVAL_DIR}/include/MenuTextRenderer.h
    ${OPEN_RIVAL_DIR}/include/MidiContainer.h
    ${OPEN_RIVAL_DIR}/include/MidiFile.h
    ${OPEN_RIVAL_DIR}/include/MidiPlayer.h
    ${OPEN_RIVAL_DIR}/include/MidsDecoder.h
    ${OPEN_RIVAL_DIR}/include/MouseHandlerComponent.h
    ${OPEN_RIVAL_DIR}/include/MousePicker.h
    ${OPEN_RIVAL_DIR}/include/MouseUtils.h
    ${OPEN_RIVAL_DIR}/include/MoveCommand.h
    ${OPEN_RIVAL_DIR}/include/MovementComponent.h
    ${OPEN_RIVAL_DIR}/include/OwnerComponent.h
    ${OPEN_RIVAL_DIR}/include/Palette.h
    ${OPEN_RIVAL_DIR}/include/PaletteUtils.h
    ${OPEN_RIVAL_DIR}/include/PassabilityComponent.h
    ${OPEN_RIVAL_DIR}/include/PathUtils.h
    ${OPEN_RIVAL_DIR}/include/Pathfinding.h
    ${OPEN_RIVAL_DIR}/include/PlayerContext.h
    ${OPEN_RIVAL_DIR}/include/PlayerState.h
    ${OPEN_RIVAL_DIR}/include/PortraitComponent.h
    ${OPEN_RIVAL_DIR}/include/ProgramOptions.h
    ${OPEN_RIVAL_DIR}/include/Race.h
    ${OPEN_RIVAL_DIR}/include/Rect.h
    ${OPEN_RIVAL_DIR}/include/RenderUtils.h
    ${OPEN_RIVAL_DIR}/include/Resources.h
    ${OPEN_RIVAL_DIR}/include/SDLWrapper.h
    ${OPEN_RIVAL_DIR}/include/ScenarioBuilder.h
    ${OPEN_RIVAL_DIR}/include/ScenarioData.h
    ${OPEN_RIVAL_DIR}/include/ScenarioReader.h
    ${OPEN_RIVAL_DIR}/include/SeafarerComponent.h
    ${OPEN_RIVAL_DIR}/include/ShaderUtils.h
    ${OPEN_RIVAL_DIR}/include/Shaders.h
    ${OPEN_RIVAL_DIR}/include/SoundSource.h
    ${OPEN_RIVAL_DIR}/include/Sounds.h
    ${OPEN_RIVAL_DIR}/include/SpriteComponent.h
    ${OPEN_RIVAL_DIR}/include/SpriteRenderable.h
    ${OPEN_RIVAL_DIR}/include/Spritesheet.h
    ${OPEN_RIVAL_DIR}/include/State.h
    ${OPEN_RIVAL_DIR}/include/StringUtils.h
    ${OPEN_RIVAL_DIR}/include/TextRenderable.h
    ${OPEN_RIVAL_DIR}/include/TextRenderer.h
    ${OPEN_RIVAL_DIR}/include/Texture.h
    ${OPEN_RIVAL_DIR}/include/TextureAtlas.h
    ${OPEN_RIVAL_DIR}/include/Tile.h
    ${OPEN_RIVAL_DIR}/include/TileRenderer.h
    ${OPEN_RIVAL_DIR}/include/TimeUtils.h
    ${OPEN_RIVAL_DIR}/include/UiRenderer.h
    ${OPEN_RIVAL_DIR}/include/Unit.h
    ${OPEN_RIVAL_DIR}/include/UnitAnimationComponent.h
    ${OPEN_RIVAL_DIR}/include/UnitDef.h
    ${OPEN_RIVAL_DIR}/include/UnitPropsComponent.h
    ${OPEN_RIVAL_DIR}/include/VoiceComponent.h
    ${OPEN_RIVAL_DIR}/include/WalkerComponent.h
    ${OPEN_RIVAL_DIR}/include/WallComponent.h
    ${OPEN_RIVAL_DIR}/include/WaveFile.h
    ${OPEN_RIVAL_DIR}/include/Window.h
    ${OPEN_RIVAL_DIR}/include/World.h
    ${OPEN_RIVAL_DIR}/include/commands/GameCommandFactory.h
    ${OPEN_RIVAL_DIR}/include/gfx/BoxRenderable.h
    ${OPEN_RIVAL_DIR}/include/gfx/GlewWrapper.h
    ${OPEN_RIVAL_DIR}/include/gfx/TextureRenderable.h
    ${OPEN_RIVAL_DIR}/include/lobby/LobbyState.h
    ${OPEN_RIVAL_DIR}/include/net/ClientInfo.h
    ${OPEN_RIVAL_DIR}/include/net/Connection.h
    ${OPEN_RIVAL_DIR}/include/net/NetUtils.h
    ${OPEN_RIVAL_DIR}/include/net/PacketFactory.h
    ${OPEN_RIVAL_DIR}/include/net/Server.h
    ${OPEN_RIVAL_DIR}/include/net/Socket.h
    ${OPEN_RIVAL_DIR}/include/net/packet-handlers/AcceptPlayerPacketHandler.h
    ${OPEN_RIVAL_DIR}/include/net/packet-handlers/GameCommandPacketHandler.h
    ${OPEN_RIVAL_DIR}/include/net/packet-handlers/KickPlayerPacketHandler.h
    ${OPEN_RIVAL_DIR}/include/net/packet-handlers/LobbyWelcomePacketHandler.h
    ${OPEN_RIVAL_DIR}/include/net/packet-handlers/PacketHandler.h
    ${OPEN_RIVAL_DIR}/include/net/packet-handlers/RejectPlayerPacketHandler.h
    ${OPEN_RIVAL_DIR}/include/net/packet-handlers/RequestJoinPacketHandler.h
    ${OPEN_RIVAL_DIR}/include/net/packet-handlers/StartGamePacketHandler.h
    ${OPEN_RIVAL_DIR}/include/net/packets/AcceptPlayerPacket.h
    ${OPEN_RIVAL_DIR}/include/net/packets/GameCommandPacket.h
    ${OPEN_RIVAL_DIR}/include/net/packets/KickPlayerPacket.h
    ${OPEN_RIVAL_DIR}/include/net/packets/LobbyWelcomePacket.h
    ${OPEN_RIVAL_DIR}/include/net/packets/Packet.h
    ${OPEN_RIVAL_DIR}/include/net/packets/RejectPlayerPacket.h
    ${OPEN_RIVAL_DIR}/include/net/packets/RelayedPacket.h
    ${OPEN_RIVAL_DIR}/include/net/packets/RequestJoinPacket.h
    ${OPEN_RIVAL_DIR}/include/net/packets/StartGamePacket.h
    ${OPEN_RIVAL_DIR}/include/ui/CursorRenderer.h
    ${OPEN_RIVAL_DIR}/include/ui/MenuRenderer.h
    ${OPEN_RIVAL_DIR}/include/utils/BufferUtils.h
)
