name: cppcheck-action
on:
  workflow_dispatch:
jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g cppcheck
      - run: |
          cd Open-Rival
          cppcheck --project=Open-Rival.vcxproj "--project-configuration=Release|x64"
